{% set version = "1.0.1" %}

package:
  name: gridfill
  version: {{ version }}

source:
  url: https://github.com/ajdawson/gridfill/archive/v{{ version }}.tar.gz
  sha256: 39d415da855e62d95f9e6221efbe9ee66605f83db217eeac559ded8678158e47

build:
  number: 0
  skip: True  # [win and py2k]
  script:
    - python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python
    - pip
    - cython
    - numpy 1.11.*
  run:
    - python
    - numpy >=1.11,<1.12

test:
  requires:
    - nose
  imports:
    - gridfill
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
    home: https://github.com/ajdawson/gridfill
    license: MIT
    license_file: COPYING
    summary: "Fill missing values in a grid by solving Poisson's equation via an iterative relaxation scheme"

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
