{% set version = "1.1.1" %}

package:
  name: gridfill
  version: {{ version }}

source:
  url: https://github.com/ajdawson/gridfill/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5375dbf90e9f1192ada8af545c1c67a4da91c422a10074fcac7316e9e3c6eabe

build:
  number: 3
  skip: true  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.0
    - numpy
  run:
    - python

test:
  imports:
    - gridfill
  requires:
    - pytest
  commands:
    - pytest --pyargs gridfill.tests

about:
  home: https://github.com/ajdawson/gridfill
  license: MIT
  license_file: COPYING
  summary: "Fill missing values in a grid by solving Poisson's equation via an iterative relaxation scheme"

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
