appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OrwqmBFI7Sdn7DNVFhU3rHsCm0JyLTmh8rC9j+N+97+qbkB6FQ2QK/TrarSXId8G7BjHlVZVgz+0fTyWITJVZWgAG/3Q4WzswHbtUoIwUUOmp/Agq1JBJV6XBOorKeCvYmSD2GQ6bP0jF0YQyt9FPfpSzhSW1nONKYpBKkjbtVpX4lHm1UboCld6BynQqW2vCNeLlUxK4+XFYG74a0T8QvmXOtnh8p2iqOB6LaSUvMMZKZ9a3xvOyy0Q43TaV4pLtDJY3e+FPjj0LiXQbdlXAjNW7PXGG1Bt16+15lIDC2hY+o4pdYK2ZSYDn2ySTNA0GG7WSlx1kkvDcwKEwu99SkgCC/IWDkR/f93IxWMe5O1J+S4onLX5GUzVjBTiTsbXbiYWAHMPPBv7au/f/L9H/Y9tVKVjrZ84Gj/l04x3eFtEp56Q6KZ+BCTUWZVZtJikp+HWT4KbeEFTSnUKDbQvjf04MPHJsgTMfJ0PMS8CFdS+weAo+TY5xVRoKkUVvq+TuRFJWgskwi9nQUCcDkj1Wwg9LhbQC1GSwqjWb4p8dvxw/G8n87XTcrMOszSFL6n14Y6VqJcPXTilA5vSQnZXeEF1jbgmnsbA3dcM71KzFcAOI2eS8eESFjnCqAIpUB3d2ZUMdYXidRZ+4qlDxOSq3Es+HjKF6GPMj7GHmgqdrec=}
